version: "3.7"
services:
  db:
    build: "./backend/db/"
    ports:
      - '3307:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
       MYSQL_DATABASE: 'transactions'
       MYSQL_USER: 'toro'
       MYSQL_PASSWORD: '77991717025'
       MYSQL_ROOT_PASSWORD: '77991717025'
    volumes:
      - ./backend/db/data:/var/lib/mysql
    restart: always

  transactions_service:
    restart: always
    build: "./backend/services/transactions/"
    container_name: transactions-service
    command: /bin/sh -c 'python manage.py makemigrations --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8082'
    volumes:
      - ./backend/services/transactions/:/code/app/
    ports:
      - 8082:8082
    env_file:
      - ./backend/services/transactions/.env
    depends_on:
      - db
    links:
      - db:db

  quotes_service:
    build: "./backend/services/quotes/"
    container_name: quotes-service
    volumes:
      - ./backend/services/quotes/:/code/app/
    ports:
      - 8080:8080

  app:
    build: "./app/"
    restart: always
    container_name: app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 4200:4200
    depends_on: 
      - transactions_service
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

