version: "3.7"
services:
  db:
    build: "./backend/db/"
    ports:
      - '3307:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
       MYSQL_DATABASE: 'transactions'
       MYSQL_USER: 'toro'
       MYSQL_PASSWORD: '77991717025'
       MYSQL_ROOT_PASSWORD: '77991717025'
    volumes:
      - ./backend/db/data:/var/lib/mysql
    restart: always
    
  quotes_service:
    build: "./backend/services/quotes/"
    container_name: quotes-service
    volumes:
      - ./backend/services/quotes/:/code/app/
    ports:
      - 8080:8080

