version: "3.7"
services:
  app:
    restart: always
    build: "./app/"
    container_name: trade-app
    ports:
      - 8081:80
    depends_on:
      - transactions_service

  transactions_service:
    restart: always
    build: "./backend/services/transactions/"
    container_name: transactions-service
    command: /bin/sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8082'
    volumes:
      - ./backend/services/transactions/:/code/app/
    ports:
      - 8082:8082
    env_file:
      - ./backend/services/transactions/.env
    depends_on:
      - db
    links:
      - db:db

  db:
    build: "./backend/db/"
    ports:
      - '3307:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
       MYSQL_DATABASE: 'transactions'
       MYSQL_USER: 'toro'
       MYSQL_PASSWORD: '77991717025'
       MYSQL_ROOT_PASSWORD: '77991717025'
    volumes:
      - ./backend/db/data:/var/lib/mysql
    restart: always

  quotes_service:
    build: "./backend/services/quotes/"
    container_name: quotes-service
    volumes:
      - ./backend/services/quotes/:/code/app/
    ports:
      - 8080:8080

