# Generated by Django 2.2.6 on 2019-12-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('operation_type', models.CharField(blank=True, choices=[('sell', 'Draw'), ('bought', 'Deposit')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('draw', 'Draw'), ('deposit', 'Deposit')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
