# Generated by Django 2.2.6 on 2019-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191213_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('draw', 'Draw'), ('deposit', 'Deposit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('sell', 'Draw'), ('bought', 'Deposit')], max_length=10, null=True),
        ),
    ]
